"""тест настроек Decimal

Revision ID: 0e36f9f9807e
Revises: 917bb5bb3e5a
Create Date: 2025-01-08 19:37:18.777167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e36f9f9807e"
down_revision: Union[str, None] = "917bb5bb3e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_rates",
        "rate",
        existing_type=sa.NUMERIC(precision=6, scale=6),
        type_=sa.DECIMAL(precision=6, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_rates",
        "rate",
        existing_type=sa.DECIMAL(precision=6, scale=2),
        type_=sa.NUMERIC(precision=6, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
