"""определение отношения 3

Revision ID: 22e8c9234f1d
Revises: 45dcfbb8e58d
Create Date: 2025-01-06 22:16:59.713377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22e8c9234f1d"
down_revision: Union[str, None] = "45dcfbb8e58d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
