"""определение отношения 2

Revision ID: 45dcfbb8e58d
Revises: 19beb4e78304
Create Date: 2025-01-06 22:14:40.508522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45dcfbb8e58d"
down_revision: Union[str, None] = "19beb4e78304"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
