"""fix name currencies

Revision ID: 4cf744cc5a4f
Revises: 6bfc98c4910a
Create Date: 2024-12-31 00:49:04.680361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cf744cc5a4f"
down_revision: Union[str, None] = "6bfc98c4910a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currencies",
        sa.Column("full_name", sa.String(length=50), nullable=False),
    )
    op.drop_column("currencies", "fill_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currencies",
        sa.Column(
            "fill_name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("currencies", "full_name")
    # ### end Alembic commands ###
