"""определение отношения 4

Revision ID: 917bb5bb3e5a
Revises: 22e8c9234f1d
Create Date: 2025-01-06 22:32:27.615492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "917bb5bb3e5a"
down_revision: Union[str, None] = "22e8c9234f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
