"""изменение Decimal

Revision ID: 99312dcad293
Revises: 0e36f9f9807e
Create Date: 2025-01-15 19:18:06.492645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99312dcad293"
down_revision: Union[str, None] = "0e36f9f9807e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_rates",
        "rate",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        type_=sa.DECIMAL(precision=9, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange_rates",
        "rate",
        existing_type=sa.DECIMAL(precision=9, scale=6),
        type_=sa.NUMERIC(precision=6, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
